### ISSUE TITLE
Site needs update

### ISSUE THREAD

**Issue by crashr** [xCuri0/ReBarUEFI#192]
Hi.
I think the info about ifrextract is outdated. I just used ifrextract on linux without any issues.
https://github.com/xCuri0/ReBarUEFI/wiki/Enabling-hidden-4G-decoding

**Comment by MrAnonymous7122** [comment]
@xCuri0 I've updated the [wiki page](https://github.com/MrAnonymous7122/ReBarUEFI/wiki/Enabling-Hidden-4G-Decoding) but github unfortunately does not allow pull requests for wiki. My updated guide uses [IFRExtractor-RS](https://github.com/LongSoft/IFRExtractor-RS/releases/) instead of the archived [Universal IFR Extractor](https://github.com/LongSoft/Universal-IFR-Extractor/releases).  [IFRExtractor-RS](https://github.com/LongSoft/IFRExtractor-RS/releases/) also works on linux.

**Comment by xCuri0** [comment]
@MrAnonymous7122 Thx, I've updated the wiki with it
