### ISSUE TITLE
Injection possible using bootloader?

### ISSUE THREAD

**Issue by Schaka** [xCuri0/ReBarUEFI#6]
Hi,

I'm wondering if it's possible to inject the driver using a bootloader like Clover, OpenCore or DUET.
OEM systems usually have some sort of module that disables any BIOS mods by recognizing modifications and refusing to POST with some sort of checksum error (they usually have beep codes for that).

I feel like the real strength of your mod are budget OEM systems, Chinese X99 where you mod the BIOS anyway and maybe LGA 1151 mutants like the QTJ2 that already require a BIOS mod to make Coffee Lake mobile processors work on Skylake/Kaby Lake boards.

What I'm trying to figure out is if there's a way to serve the one budget group that seems less easy. I know in the past people have used bootloaders to get around older BIOSes not supporting boot from PCIe because they can't mod the BIOS itself. I'd appreciate any info you have.

Currently don't have any OEM system on hand to test this, but a B350 one that doesn't have a BIOS update with ReBar that I could test any suggestions. I think it could be valuable info added to your documentation as well.

**Comment by xCuri0** [comment]
> I'm wondering if it's possible to inject the driver using a bootloader like Clover, OpenCore or DUET.

No because it will then be loaded after PCI enumeration has finished so the hooked PreprocessController never gets run.

I did initially make a version that runs from a bootloader though but it's a hardcoded mess that only works if you use CSM on and makes your boot screen rainbows till the GPU driver loads. Commit [4e9175badbf7a4d75ef6ac4c4c92897dc559b7ae](https://github.com/xCuri0/ReBarUEFI/tree/4e9175badbf7a4d75ef6ac4c4c92897dc559b7ae) providing as-is it's not going to work without modifications to the hardcoded addresses. Also it makes GPU-Z say Resizable BAR is off for some reason and I never tested if it gives a performance gain (unlike the UEFI DXE driver which I confirmed does)
